services:
  front:
    build: 
      dockerfile: ./front/Dockerfile
    volumes:
      - ./scripts/nginx.conf /etc/nginx/conf.d/default.conf
    ports:
      - 8081:80 
    
      
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest	
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=SQLServer2023!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
  
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    volumes:
      - ./scriopts/init-db.sql:/tmp/init-db.sql
      - ./scripts/init.sh:init.sh
    
  api:
    image: api
    build:
      dockerfile: ./api/Dockerfile
    ports:
      - 5223:5223
  
