services:
  front:
    image: front
    build: 
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80 
    
      
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest	
    container_name: db
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=SQLServer2023!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
  
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssqltools
    depends_on:
      - db
    volumes:
      - ./scripts/init-db.sql:/tmp/init-db.sql
      - ./scripts/init.sh:/tmp/init.sh
    command: /bin/bash ./tmp/init.sh

  api:
    image: api
    build:
      dockerfile: ./api/Dockerfile
    ports:
      - 5223:5223
  
